export const CoursesInfo = [
  {
    id: "1",
    title: "Sesión 1",
    date: "jueves, 21 de marzo de 2024",
    schedule: "jueves, 21 de marzo de 2024 a las 5:55 AM",
    attendance: "Asistencia marcada",
    description: "Descripción de la Sesión 1",
    status: "Finalizado",
    recordingLink: "#",
  },
  {
    id: "2",
    title: "Sesión 2",
    date: "viernes, 22 de marzo de 2024",
    schedule: "viernes, 22 de marzo de 2024",
    attendance: "",
    description: "",
    status: "Finalizado",
    recordingLink: "#",
  },
  {
    id: "3",
    title: "Sesión 3",
    date: "sábado, 23 de marzo de 2024",
    schedule: "sábado, 23 de marzo de 2024 a las 10:00 AM",
    attendance: "Asistencia marcada",
    description: "Descripción de la Sesión 3",
    status: "Finalizado",
    recordingLink: "#",
  },
  {
    id: "4",
    title: "Sesión 4",
    date: "domingo, 24 de marzo de 2024",
    schedule: "domingo, 24 de marzo de 2024 a las 11:00 AM",
    attendance: "Asistencia marcada",
    description: "Descripción de la Sesión 4",
    status: "Finalizado",
    recordingLink: "#",
  }
];
